### ISSUE TITLE
Encoder generates unneeded indentation and new lines

### ISSUE THREAD

**Issue by legendik** [nette/neon#20]
Let's have following `messagess.neon` file:
```
a:
	b: Some text
	c: Some other text
	d: someKey:
		e: Some next message
f: Hello world
```

We want to parse this file by `Decoder`, the decoded values encode by `Encoder` and save the file back, because we want fix "Neon coding standards" in this file. Like remove unneeded `"`,`'` etc...

The common problem is, that the `Encoder` properly fix the `Neon coding standards`, but generates also unneeded newlines and tabs.

Let's have following code:

```php
$file = file_get_contents('messages.neon');
$decoder = new Decoder;
$decoded = $decoder->decode($file);
$encoder = new Encoder;
$encoded = $encoder->encode($decoded, Encoder::BLOCK);
file_put_contents('messages.neon', $encoded);
```

And the result of `messages.neon`?

```
a:
	b: Some text
	c: Some other text
	d: someKey:
		e: Some next message
		#two tabs
	#one tab
f: Hello world
```

**Comment by dg** [comment]
Is this valid?
```
d: someKey:
    e: Some next message
```

**Comment by legendik** [comment]
Thanks @dg! One more think, it still generates two unneeded newlines instead of one. For example:
```
a:
    b: Some text
    c: Some other text
    d: someKey:
        e: Some next message
#newLine
#newLine
f: Hello world
```

Is this valid, or can be fixed as well?

**Comment by dg** [comment]
Fixed

**Comment by legendik** [comment]
Not properly :)
```
restaurant:
     notes:
          key1: Some message1
          key2: Some Message2
          key3: Some message3
disagreementState:
     key4: Some message4
```

Generates still two newlines:
```
restaurant:
     notes:
          key1: Some message1
          key2: Some Message2
          key3: Some message3
#first newline
#second newline
disagreementState:
     key4: Some message4
```
